// 6 Core Services for Comprehensive IT Solutions
export const allServices = [
  {
    id: 1,
    number: "01",
    title: "Product & Software Development",
    shortTitle: "Product & Software Development",
    displayTitle: "Product Development",
    subtitle: "End-to-End Custom Engineering",
    description: "End-to-end product development that turns ideas into powerful digital solutions.",
    details: "We specialize in full-lifecycle software engineering. From early-stage MVP prototyping to high-scale multi-tenant SaaS platforms, we architect custom digital products that scale seamlessly.",
    image: "/images/services/01-product-dev.jpg",
    cardImage: "/images/services/card-01.png",
    deliveryTime: "4–16 weeks",
    projectsCompleted: "350+",
    rating: 4.9,
    iconType: "code",
    theme: {
      accent: "#38bdf8",
      glowColor: "rgba(56, 189, 248, 0.35)",
      borderColor: "border-sky-500/40",
      shapeClass: "rounded-t-[32px] rounded-b-[48px] rounded-br-[60px]",
      pillActive: "border-sky-400 bg-sky-950/40 text-sky-200"
    },
    subServices: ["Product Development", "SaaS Development", "MVP Development", "Custom Solutions"],
    features: [
      "Custom Software Architecture",
      "Multi-tenant SaaS Platforms",
      "Rapid MVP Development",
      "Subscription Billing & Auth",
      "Agile Lifecycle Management",
      "Post-Launch Scalability"
    ],
  },
  {
    id: 2,
    number: "02",
    title: "UI/UX Design",
    shortTitle: "UI/UX Design",
    displayTitle: "UI/UX Design",
    subtitle: "Research-Driven Digital Experiences",
    description: "Designing intuitive and engaging user experiences that drive real impact.",
    details: "Deliver exceptional digital experiences. Our UI/UX design discipline blends behavioral research, rapid prototyping, and scalable design systems to maximize conversion and user retention.",
    image: "/images/services/02-ui-ux.jpg",
    cardImage: "/images/services/card-02.png",
    deliveryTime: "2–6 weeks",
    projectsCompleted: "300+",
    rating: 5.0,
    iconType: "pen",
    theme: {
      accent: "#a855f7",
      glowColor: "rgba(168, 85, 247, 0.35)",
      borderColor: "border-purple-500/40",
      shapeClass: "rounded-t-[32px] rounded-tr-[32px] rounded-br-[32px] rounded-bl-[56px]",
      pillActive: "border-purple-400 bg-purple-950/40 text-purple-200"
    },
    subServices: ["User Research", "Wireframing & Prototyping", "Design Systems", "Usability Testing"],
    features: [
      "User Research & Personas",
      "Wireframing & High-Fidelity UI",
      "Interactive Prototyping",
      "Design System & Component Kits",
      "Usability Testing & Audits",
      "Multi-device Responsive UX"
    ],
  },
  {
    id: 3,
    number: "03",
    title: "Modernization & Transformation",
    shortTitle: "Modernization & Transformation",
    displayTitle: "Modernization",
    subtitle: "Legacy System Re-Architecture",
    description: "Empowering businesses with modern technology to innovate and scale.",
    details: "Modernize mission-critical enterprise systems. We refactor monolithic codebases into resilient microservices, automate operational workflows, and migrate workloads with zero disruption.",
    image: "/images/services/03-modernization.jpg",
    cardImage: "/images/services/card-03.png",
    deliveryTime: "10–24 weeks",
    projectsCompleted: "150+",
    rating: 4.8,
    iconType: "gear",
    theme: {
      accent: "#06b6d4",
      glowColor: "rgba(6, 182, 212, 0.45)",
      borderColor: "border-cyan-400/60",
      shapeClass: "rounded-[52px]",
      pillActive: "border-cyan-400 bg-cyan-950/40 text-cyan-200"
    },
    subServices: ["App Modernization", "Digital Transformation", "Cloud-Native Migration", "Legacy Refactoring"],
    features: [
      "Architecture Assessment",
      "Cloud-Native Refactoring",
      "Microservices Migration",
      "Process Automation & AI",
      "Legacy Code Modernization",
      "Zero-Downtime Cutover"
    ],
  },
  {
    id: 4,
    number: "04",
    title: "Cloud & Engineering Infrastructure",
    shortTitle: "Cloud & Engineering Infrastructure",
    displayTitle: "Cloud Infrastructure",
    subtitle: "Scalable DevOps & High-Availability APIs",
    description: "Scalable, secure, and cost-efficient cloud solutions designed for the future.",
    details: "Establish robust backbone infrastructure. We design multi-cloud environments, implement Infrastructure as Code (IaC), build automated CI/CD pipelines, and secure API gateways.",
    image: "/images/services/04-cloud-infra.jpg",
    cardImage: "/images/services/card-04.png",
    deliveryTime: "6–14 weeks",
    projectsCompleted: "200+",
    rating: 4.9,
    iconType: "cloud",
    theme: {
      accent: "#3b82f6",
      glowColor: "rgba(59, 130, 246, 0.35)",
      borderColor: "border-blue-500/40",
      shapeClass: "rounded-t-[32px] rounded-tr-[56px] rounded-b-[32px] rounded-br-[56px]",
      pillActive: "border-blue-400 bg-blue-950/40 text-blue-200"
    },
    subServices: ["Cloud Infrastructure", "DevOps Implementation", "API Development", "CI/CD Automation"],
    features: [
      "Multi-Cloud Architecture",
      "CI/CD Pipeline Automation",
      "RESTful & GraphQL APIs",
      "Infrastructure as Code (IaC)",
      "Containerization (Docker/K8s)",
      "Security & Observability"
    ],
  },
  {
    id: 5,
    number: "05",
    title: "IoT Services",
    shortTitle: "IoT Services",
    displayTitle: "IoT Services",
    subtitle: "Connected Hardware & Edge Computing",
    description: "Connecting devices and data to build smarter, faster, and more efficient solutions.",
    details: "Bridge the physical and digital domains. Our end-to-end IoT engineering covers hardware protocol integration, device fleet management, edge computing, and predictive telemetry.",
    image: "/images/services/05-iot-services.jpg",
    cardImage: "/images/services/card-05.png",
    deliveryTime: "12–18 weeks",
    projectsCompleted: "45+",
    rating: 4.9,
    iconType: "iot",
    theme: {
      accent: "#f97316",
      glowColor: "rgba(249, 115, 22, 0.45)",
      borderColor: "border-orange-500/50",
      shapeClass: "rounded-[32px]",
      pillActive: "border-orange-500 bg-orange-950/50 text-orange-200 ring-1 ring-orange-500"
    },
    subServices: ["IoT Platform Development", "Device Integration & Management", "Real-time Data Analytics", "Edge Computing"],
    features: [
      "IoT Platform Development",
      "Device Fleet Management",
      "Real-time Telemetry Analytics",
      "Edge Computing & Gateways",
      "Hardware Protocol Integration",
      "Predictive Maintenance"
    ],
  },
  {
    id: 6,
    number: "06",
    title: "ERP Solutions",
    shortTitle: "ERP Solutions",
    displayTitle: "ERP Solutions",
    subtitle: "Enterprise Resource Planning & Workflows",
    description: "Integrated ERP solutions to manage your business processes seamlessly.",
    details: "Streamline enterprise operations with tailored ERP solutions. We integrate supply chains, CRM, HR, operations, and financial workflows to scale efficiency.",
    image: "/images/services/card-06-dark.png",
    cardImage: "/images/services/card-06-dark.png",
    deliveryTime: "8–20 weeks",
    projectsCompleted: "120+",
    rating: 4.9,
    iconType: "erp",
    theme: {
      accent: "#10b981",
      glowColor: "rgba(16, 185, 129, 0.45)",
      borderColor: "border-emerald-500/50",
      shapeClass: "rounded-[32px]",
      pillActive: "border-emerald-500 bg-emerald-950/50 text-emerald-200 ring-1 ring-emerald-500"
    },
    subServices: ["Odoo ERP Implementation", "ERP Customization", "CRM & Finance", "Enterprise Automation"],
    features: [
      "Custom ERP Implementation",
      "Process Automation & Workflows",
      "Financial & HR Management",
      "Inventory & Supply Chain",
      "CRM & Sales Pipeline",
      "Third-party API Integrations"
    ],
  },
];
