export const awardsData = [
  {
    id: "award-1",
    imageSrc: "/awards/Award-1.png",
    title: "STEM & Robotics Company of the Year",
    organization: "Indian Education & EdTech Awards",
    subOrganization: "Organised by Brand Honchos • Powered by Sodexo",
    presentedTo: "Student Alliance LLP",
    year: "2023",
    date: "20th January 2023",
    location: "Hyatt Regency, Gurgaon",
    category: "STEM & EdTech",
    badge: "Company of the Year",
    theme: {
      cardBg: "#0a1b4d",
      cardGradient: "linear-gradient(145deg, #0a1b4d 0%, #1d4ed8 45%, #2563eb 72%, #5b21b6 100%)",
      domainLabel: "STEM",
      gradient: "from-amber-500/10 via-yellow-500/5 to-transparent",
      badgeBg: "bg-amber-50 text-amber-800 border-amber-200",
      accent: "#d97706",
      cardGlow: "group-hover:shadow-blue-900/40"
    },
    description: "Conferred at the Indian Education and Edtech Awards for pioneering STEM and Robotics education solutions across India."
  },
  {
    id: "award-2",
    imageSrc: "/awards/Award-2.png",
    title: "Bharat Ka Best Brand Award 2024",
    organization: "International STEM & Robotics Championship (ISRC)",
    subOrganization: "Bharat Ka Best Brand Awards",
    presentedTo: "Student Alliance",
    year: "2024",
    date: "22nd September 2024",
    location: "Hotel Taj Mahal Palace, Mumbai",
    category: "STEM & EdTech",
    badge: "Best Brand 2024",
    theme: {
      cardBg: "#072540",
      cardGradient: "linear-gradient(145deg, #072540 0%, #0284c7 40%, #06b6d4 75%, #0f766e 100%)",
      domainLabel: "ISRC",
      gradient: "from-rose-500/10 via-red-500/5 to-transparent",
      badgeBg: "bg-rose-50 text-rose-800 border-rose-200",
      accent: "#e11d48",
      cardGlow: "group-hover:shadow-teal-950/40"
    },
    description: "Honored under Technical Skill Education at the Taj Mahal Palace for educational excellence in robotics and championships."
  },
  {
    id: "award-3",
    imageSrc: "/awards/Award-3.png",
    title: "50 Years Milestone Honour & Appreciation",
    organization: "MESCO (Modern Educational Social & Cultural Org.)",
    subOrganization: "A Trust Since 1966 • Golden Jubilee Milestone",
    presentedTo: "Leadership Team",
    year: "2023",
    date: "50 Years Celebration",
    location: "Mumbai",
    category: "Institutional & CSR",
    badge: "50 Years Milestone",
    theme: {
      cardBg: "#3d1404",
      cardGradient: "linear-gradient(145deg, #3d1404 0%, #9a3412 40%, #ea580c 75%, #f59e0b 100%)",
      domainLabel: "MESCO",
      gradient: "from-amber-500/10 via-orange-500/5 to-transparent",
      badgeBg: "bg-amber-50 text-amber-900 border-amber-200",
      accent: "#b45309",
      cardGlow: "group-hover:shadow-amber-950/40"
    },
    description: "Awarded in appreciation for unwavering support and unrelenting guidance on the path to educational empowerment and success."
  },
  {
    id: "award-4",
    imageSrc: "/awards/Award-4.png",
    title: "Valued Contribution & Academic Partnership",
    organization: "Maharashtra Class Owners' Association (MCOA)",
    subOrganization: "Estd. 2000",
    presentedTo: "Student Alliance",
    year: "2024",
    date: "Annual Convention",
    location: "Maharashtra",
    category: "Institutional & CSR",
    badge: "Contribution Award",
    theme: {
      cardBg: "#0c142b",
      cardGradient: "linear-gradient(145deg, #0c142b 0%, #312e81 40%, #6b21a8 75%, #9333ea 100%)",
      domainLabel: "MCOA",
      gradient: "from-sky-500/10 via-blue-500/5 to-transparent",
      badgeBg: "bg-sky-50 text-sky-800 border-sky-200",
      accent: "#0284c7",
      cardGlow: "group-hover:shadow-purple-950/40"
    },
    description: "Presented by Maharashtra Class Owners' Association in recognition of valued contribution and collaborative educational support."
  },
  {
    id: "award-5",
    imageSrc: "/awards/Award-5.png",
    title: "Outstanding Leadership Award",
    organization: "Connects U — India Roadshow",
    subOrganization: "Connects U Global Network",
    presentedTo: "Awab Fakhi (Student Alliance)",
    year: "2025",
    date: "January 2025",
    location: "India Roadshow",
    category: "Leadership & Vision",
    badge: "Leadership Award",
    theme: {
      cardBg: "#3f0713",
      cardGradient: "linear-gradient(145deg, #3f0713 0%, #881337 40%, #be123c 75%, #fb7185 100%)",
      domainLabel: "LEAD",
      gradient: "from-red-500/10 via-amber-500/5 to-transparent",
      badgeBg: "bg-red-50 text-red-800 border-red-200",
      accent: "#dc2626",
      cardGlow: "group-hover:shadow-pink-950/40"
    },
    description: "Honoring outstanding leadership, guidance, visionary thinking, and steadfast support serving as a true source of inspiration."
  },
  {
    id: "award-6",
    imageSrc: "/awards/Award-6.png",
    title: "Saidham CSR Award for Excellence",
    organization: "Saidham Foundation",
    subOrganization: "Seva Naam Sai Initiative",
    presentedTo: "Student Alliance",
    year: "2023",
    date: "March 4th, 2023",
    location: "National CSR Conclave",
    category: "Institutional & CSR",
    badge: "Excellence in CSR",
    theme: {
      cardBg: "#0b1c4d",
      cardGradient: "linear-gradient(145deg, #0b1c4d 0%, #1e40af 40%, #2563eb 75%, #38bdf8 100%)",
      domainLabel: "CSR",
      gradient: "from-blue-500/10 via-cyan-500/5 to-transparent",
      badgeBg: "bg-blue-50 text-blue-800 border-blue-200",
      accent: "#2563eb",
      cardGlow: "group-hover:shadow-blue-900/40"
    },
    description: "Recognizing dedicated contributions and excellence in the field of Corporate Social Responsibility (CSR) and community uplifting."
  },
  {
    id: "award-7",
    imageSrc: "/awards/Award-7.png",
    title: "14th All India Educational Conference Honour",
    organization: "AIEM in Collaboration with SECAB",
    subOrganization: "SECAB Institute of Engineering & Technology",
    presentedTo: "Dr. Awab Fakih (Director, Student Alliance LLP)",
    year: "2024",
    date: "8th, 9th & 10th November 2024",
    location: "Vijayapura, Karnataka",
    category: "Institutional & CSR",
    badge: "National Conference",
    theme: {
      cardBg: "#3a2003",
      cardGradient: "linear-gradient(145deg, #3a2003 0%, #78350f 40%, #b45309 75%, #f59e0b 100%)",
      domainLabel: "SECAB",
      gradient: "from-yellow-500/10 via-amber-500/5 to-transparent",
      badgeBg: "bg-amber-50 text-amber-900 border-amber-200",
      accent: "#b45309",
      cardGlow: "group-hover:shadow-yellow-950/40"
    },
    description: "Presented by Shri S. A. Punekar (Founder & President, SECAB) on the occasion of the International Engineering & Tech Conference."
  },
  {
    id: "award-8",
    imageSrc: "/awards/Award-8.png",
    title: "Global Entrepreneurship Summit Honour",
    organization: "Jai Hind College (Autonomous)",
    subOrganization: "Entrepreneurship Cell & Skill Hub (Under RUSA)",
    presentedTo: "Mr. Awab Fakih",
    year: "2024",
    date: "Summit 2024",
    location: "Mumbai",
    category: "Entrepreneurship",
    badge: "GES 2024",
    theme: {
      cardBg: "#042523",
      cardGradient: "linear-gradient(145deg, #042523 0%, #134e4a 40%, #0f766e 75%, #14b8a6 100%)",
      domainLabel: "SUMMIT",
      gradient: "from-cyan-500/10 via-blue-500/5 to-transparent",
      badgeBg: "bg-cyan-50 text-cyan-800 border-cyan-200",
      accent: "#0891b2",
      cardGlow: "group-hover:shadow-teal-950/40"
    },
    description: "Honored by Jai Hind College's E-Cell & Skill Hub under RUSA for invaluable mentorship and support to student entrepreneurs."
  },
  {
    id: "award-9",
    imageSrc: "/awards/Award-9.png",
    title: "ConnectSouq Award for Edutech Innovation",
    organization: "ConnectSouq Global Leaders Forum",
    subOrganization: "Transforming the Future of Ethical Business",
    presentedTo: "Awab Fakhi (CEO, Student Alliance)",
    year: "2025",
    date: "8th November 2025",
    location: "Millennium Plaza Downtown Hotel, Dubai",
    category: "STEM & EdTech",
    badge: "Global Innovation",
    theme: {
      cardBg: "#032b21",
      cardGradient: "linear-gradient(145deg, #032b21 0%, #064e3b 40%, #059669 75%, #10b981 100%)",
      domainLabel: "EDTECH",
      gradient: "from-emerald-500/10 via-teal-500/5 to-transparent",
      badgeBg: "bg-emerald-50 text-emerald-800 border-emerald-200",
      accent: "#059669",
      cardGlow: "group-hover:shadow-teal-900/40"
    },
    description: "International recognition conferred in Dubai honoring global leaders driving ethical business, EdTech innovation, and cross-border collaboration."
  },
  {
    id: "award-10",
    imageSrc: "/awards/Award-10.png",
    title: "Token of Appreciation — Vocational Excellence",
    organization: "AWT Edu Trust Raigad",
    subOrganization: "Mehrunnisa Abbas Fakih ITI Mazgaon (Estd. 2006)",
    presentedTo: "Student Alliance",
    year: "2024",
    date: "Annual Convocation",
    location: "Mazgaon, Raigad",
    category: "Institutional & CSR",
    badge: "Vocational Support",
    theme: {
      cardBg: "#1c1917",
      cardGradient: "linear-gradient(145deg, #1c1917 0%, #292524 40%, #44403c 75%, #78716c 100%)",
      domainLabel: "TRUST",
      gradient: "from-amber-600/10 via-stone-500/5 to-transparent",
      badgeBg: "bg-stone-100 text-stone-800 border-stone-200",
      accent: "#78350f",
      cardGlow: "group-hover:shadow-stone-900/40"
    },
    description: "Token of deep appreciation from AWT Edu Trust Raigad for sustained commitment toward vocational training and youth empowerment."
  },
  {
    id: "award-11",
    imageSrc: "/awards/Award-11.png",
    title: "Inauguration of ATAL Tinkering Lab & Range",
    organization: "The Greenfingers School, Akluj",
    subOrganization: "Estd. 1975 • Founder Sahakar Maharshi Shri Shankarrao Mohite-Patil",
    presentedTo: "Student Alliance Implementation Team",
    year: "2022",
    date: "12th February 2022",
    location: "Akluj, Maharashtra",
    category: "STEM & EdTech",
    badge: "ATL Inauguration",
    theme: {
      cardBg: "#052342",
      cardGradient: "linear-gradient(145deg, #052342 0%, #0369a1 40%, #0284c7 75%, #38bdf8 100%)",
      domainLabel: "ATAL",
      gradient: "from-sky-500/10 via-indigo-500/5 to-transparent",
      badgeBg: "bg-sky-50 text-sky-800 border-sky-200",
      accent: "#0369a1",
      cardGlow: "group-hover:shadow-sky-900/40"
    },
    description: "Memento commemorating the landmark inauguration and establishment of the ATAL Tinkering Lab (ATL) and shooting range facility."
  },
  {
    id: "award-12",
    imageSrc: "/awards/Award-12.png",
    title: "Keynote Speaker Honor — CARE Incubation",
    organization: "Maharashtra College of Arts, Science & Commerce",
    subOrganization: "Centre for Acceleration & Research Incubation Centre (CARE)",
    presentedTo: "Mr. Abdullah Hassan (Keynote Speaker)",
    year: "2025",
    date: "8th January 2025",
    location: "Mumbai University Affiliated Campus",
    category: "Leadership & Vision",
    badge: "Keynote Speaker",
    theme: {
      cardBg: "#280b45",
      cardGradient: "linear-gradient(145deg, #280b45 0%, #581c87 40%, #7e22ce 75%, #a855f7 100%)",
      domainLabel: "CARE",
      gradient: "from-amber-500/10 via-rose-500/5 to-transparent",
      badgeBg: "bg-amber-50 text-amber-900 border-amber-200",
      accent: "#b45309",
      cardGlow: "group-hover:shadow-purple-950/40"
    },
    description: "Token of Love, Respect & Gratitude presented by Chairman Dr. Sirajuddin Chouglo and Head of CARE Dr. Saima Shaikh for keynote address."
  },
  {
    id: "award-13",
    imageSrc: "/awards/Award-13.png",
    title: "Institutional Appreciation & Empowerment Memento",
    organization: "AWT Edu Trust Raigad",
    subOrganization: "Mehrunnisa Abbas Fakih ITI Mazgaon (Estd. 2006)",
    presentedTo: "Student Alliance Leadership",
    year: "2023",
    date: "Foundation Day",
    location: "Mazgaon",
    category: "Institutional & CSR",
    badge: "Appreciation Memento",
    theme: {
      cardBg: "#381a05",
      cardGradient: "linear-gradient(145deg, #381a05 0%, #78350f 40%, #92400e 75%, #d97706 100%)",
      domainLabel: "ITI",
      gradient: "from-amber-600/10 via-yellow-600/5 to-transparent",
      badgeBg: "bg-amber-50 text-amber-900 border-amber-200",
      accent: "#92400e",
      cardGlow: "group-hover:shadow-amber-950/40"
    },
    description: "Special carved wood trophy honoring invaluable technical guidance and dedicated institutional mentorship for skill development."
  },
  {
    id: "award-14",
    imageSrc: "/awards/Award-14.png",
    title: "Entrepreneurship Development Skills Honor",
    organization: "Rizvi College of Arts, Science & Commerce",
    subOrganization: "Rizvi Education Society",
    presentedTo: "Abdulla Hassan Thakur (Founder, Connect Souq & Chair GIC)",
    year: "2024",
    date: "Faculty & Student Masterclass",
    location: "Bandra, Mumbai",
    category: "Entrepreneurship",
    badge: "Masterclass Honor",
    theme: {
      cardBg: "#0c1a40",
      cardGradient: "linear-gradient(145deg, #0c1a40 0%, #1e40af 40%, #2563eb 75%, #60a5fa 100%)",
      domainLabel: "BIZ",
      gradient: "from-blue-500/10 via-sky-500/5 to-transparent",
      badgeBg: "bg-blue-50 text-blue-800 border-blue-200",
      accent: "#1d4ed8",
      cardGlow: "group-hover:shadow-blue-900/40"
    },
    description: "Awarded by Rizvi College for delivering an inspiring masterclass on Entrepreneurship Development Skills and Global Business Strategies."
  }
];

export const awardStats = [
  { value: "14+", label: "Prestigious Accolades", subtitle: "National & Global Honors", color: "#1e40af" },
  { value: "100%", label: "Authentic Inscriptions", subtitle: "Verified Industry Trophies", color: "#f97316" },
  { value: "10+", label: "Partner Institutions", subtitle: "Universities & Foundations", color: "#059669" },
  { value: "2022–25", label: "Years of Impact", subtitle: "Continuous Excellence", color: "#7c3aed" }
];

export const awardCategories = [
  { id: "all", label: "All Awards (14)" },
  { id: "STEM & EdTech", label: "STEM & EdTech" },
  { id: "Leadership & Vision", label: "Leadership" },
  { id: "Entrepreneurship", label: "Entrepreneurship" },
  { id: "Institutional & CSR", label: "Institutional & CSR" },
];
